### ISSUE TITLE
Frontend panics on non-trivial `const` generics

### ISSUE THREAD

**Issue by karthik-cryspen** [hacspec/hacspec-v2#120]
The unwrap on this line triggers a panic in the frontend:
https://github.com/hacspec/hacspec-v2/blob/5ab88beee79621aea5f04ac640a6b18573f67e01/frontend/exporter/src/all.rs#L1553

The example that triggers this is:```
fn to_le_u32s<const L: usize>(bytes: &[u8]) -> [u32; L] {
    ...
}```

**Comment by W95Psp** [comment]
Yes, we need proper support for constants, for now, the frontend really just expect a literal and nothing else!

**Comment by karthikbhargavan** [comment]
Let's start by throwing a reasonable error in this case

**Comment by W95Psp** [comment]
This is closed by #138 or #129
