### ISSUE TITLE
Upgrade Rust Version

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hacspec-v2#130]
- [ ] Update to the most recent Rust nightly
- [ ] Set recurring task to do this every 3 months

**Comment by W95Psp** [comment]
Isn't that a duplicate of #19?

**Comment by franziskuskiefer** [comment]
If that's what's supposed to happen there? The title says something else. In any case we are on a 6+ month old version now and have to update. Feel free to close this and change #19.
