### ISSUE TITLE
Invalid "cycle detected when building THIR"

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hacspec-v2#152]
The following code

```rust
fn inner_fun<const LEN: usize>() -> [u8; LEN] {
    [0u8; LEN]
}

pub fn fun() {
    const LEN: usize = 5;
    inner_fun::<LEN>();
}
```

generates the error

```
error[E0391]: cycle detected when building THIR for `fun::{constant#0}`
   --> src/lib.rs:166:17
    |
166 |     inner_fun::<LEN>();
    |                 ^^^
    |
note: ...which requires type-checking `fun::{constant#0}`...
   --> src/lib.rs:166:17
    |
166 |     inner_fun::<LEN>();
    |                 ^^^
...
```

when running `cargo hax into fstar`.

Since `cargo +nightly-2023-06-02 build` works fine this doesn't appear to be an actual `rustc` issue but a `hax` bug.

Note that the error goes away when using the literal `5` directly instead of defining the `const LEN` first.

**Comment by W95Psp** [comment]
After investigating, that's indeed related to the way the exporter browses & typecheck the crate.

This is related to [feed_anon_const_type](http://localhost:8000/rustc_middle/ty/context/struct.TyCtxt.html#method.feed_anon_const_type)

**Comment by franziskuskiefer** [comment]
Do you have any updates on this @W95Psp ?

**Comment by W95Psp** [comment]
Status: this really occurs less, but still, it occurs
