### ISSUE TITLE
Traits types not instance of correct traits

### ISSUE THREAD

**Issue by cmester0** [hacspec/hacspec-v2#227]
When generating code for traits the instance exported is not for the correct trait, e.g.
```rust
pub trait Group {
    type group_type : PartialEq + Eq + Clone + Copy;
}
```
is exported to
```fstar
class t_Group (v_Self: Type) = {
  group_type:Type;
  group_type_implements_t_Group:t_Group self;
}
```
and not an instance for each of `PartialEq`, `Eq`, `Clone`, and `Copy`

**Comment by W95Psp** [comment]
Thanks, that's very odd, and I feel we already had this bug and fixed it at some point...
Gonna look into it.
Clearly, there's some bad mapping or something: group_type is not even supposed to implement Group :o

**Comment by cmester0** [comment]
Maybe I just rebased onto a version, where it was not fixed.

**Comment by W95Psp** [comment]
Found our discussion: https://hacspec.zulipchat.com/#narrow/stream/269544-general/topic/Extend.20of.20trait.20support
it's the same thing, isn't it?
