### ISSUE TITLE
Link to the DeterminateSystems Nix installer

### ISSUE THREAD

**Issue by rasmus-kirk** [hacspec/hacspec-v2#7]
Just a suggestion to also link to the [DeterminateSystems Nix installer](https://determinate.systems/posts/determinate-nix-installer) in the readme as it comes with flake support preconfigured.

**Comment by W95Psp** [comment]
Hi, thank you, I actually didn't know that thing existed, the installer seems nice!
I'm going to change the README to mention it then.
